version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf.default
      - ./nginx.conf:/etc/nginx/nginx.conf
