version: '3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ../html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf.default
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  mbtiles:
    build:
      context: ..
      dockerfile: docker/mbtiles-server.Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../data/msp_inondations2019_eaulibre.mbtiles:/mbtiles-server/msp_inondations2019_eaulibre.mbtiles
      - ../data/odb_quebec_buildings.mbtiles:/mbtiles-server/odb_quebec_buildings.mbtiles
      - ../data/quebec_buildings.mbtiles:/mbtiles-server/quebec_buildings.mbtiles
    stdin_open: true
    tty: true
    restart: always
